name: Python CI

on:
  push:
    branches:
      - main

jobs:
  verifier_python:
    runs-on: ubuntu-latest

    steps:
      #Recuperer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      #Installer Python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      #Installer les dépendances
      - name: Install dependencies
        run: pip install pandas sqlalchemy psycopg2-binary python-dotenv

      #Verifier la syntaxe de tous les scripts Python
      - name: Check Python syntax
        run: python -m py_compile Python/*.py
